# -*- coding: utf-8 -*-
"""bangla_kobita_scrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SRl2EAv7PpmXJgeQu-ynvmmGs5FYBooQ
"""

!pip install requests-html

from requests_html import HTMLSession

session = HTMLSession()

def kobita(kobi):
  url = f"https://www.bangla-kobita.com/{kobi}/"
  r = session.get(url)
  kobitas = r.html.find("#poem > table")[0].text
  kobita_list = kobitas.split("\n")[2:][::2]
  # print(kobita_list)
  with open(f"{kobi}.txt", "w") as f:
    f.write(f"---{kobi}--\n")
    for i in kobita_list:
      f.write(f"{i}")
      f.write('\n')

kobita("shamsurrahman")
kobita("rabindranath")
kobita("nazrulislam")
kobita("jibanananda")
kobita("sukumar")

